### ISSUE TITLE
Any chance of upgrading elggchat to support the upstream elgg?

### ISSUE THREAD

**Issue by karnakitab** [iionly/elggchat#4]
Any chance of upgrading elggchat to support the upstream elgg 3.x? I really enjoyed elggchat.

**Comment by iionly** [comment]
If I would have had the time I would have upgraded in already. It will be available for Elgg 3 when I have the time to work on it (and the other plugins not yet upgraded for Elgg 3). But this won't happen soon but maybe rather over the course of months.
