### ISSUE TITLE
Elggchat throws null as session id

### ISSUE THREAD

**Issue by lindaravindran1612** [iionly/elggchat#5]
Hello, We are a talent platform and have implemented Elgg for the social interaction of employees and ElggChat for the messaging. We need your help with Elgg chat - when we click on a person's name to start a chat conversation, the session id is 'null' and not returning a session id (number) so unable to use chat. Please help!

**Comment by iionly** [comment]
As the issue seems to occur only with Elgg Multisite but Multisite is not officially supported by Elgg and dropped in Elgg 3 completely I'm afraid I can't try to fix it (first of all: no time to work on ony, secondly: I don't see any sense in it in the long run).
